# general settings
name: train_Without_GAN_Stage2
model_type: DiffIRS2Model
scale: 4
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

gt_size: 256
# dataset and data loader settings
datasets:
  train:
    name: DCSRD
    type: PairedImageDataset
    dataroot_gt: dataset/trainsets/trainH
    dataroot_lq: dataset/trainsets/trainX4
    meta_info_file: dataset/trainsets/meta_info.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb


    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val_1:
    name: DCSRD
    type: PairedImageDataset
    dataroot_gt: dataset/testsets/testH
    dataroot_lq: dataset/testsets/testX4
    # filename_tmpl: '{}x4'
    io_backend:
      type: disk


# network structures
network_g:
  type: DiffIRS2
  n_encoder_res: 9
  inp_channels: 3
  out_channels: 3
  dim: 64
  num_blocks: [13,1,1,1]
  num_refinement_blocks: 13
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.2
  bias: False
  LayerNorm_type: BiasFree
  n_denoise_res: 1
  linear_start: 0.1
  linear_end: 0.99
  timesteps: 4

# network structures
network_S1:
  type: DiffIRS1
  n_encoder_res: 9
  inp_channels: 3
  out_channels: 3
  dim: 64
  num_blocks: [13,1,1,1]
  num_refinement_blocks: 13
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.2
  bias: False
  LayerNorm_type: BiasFree


# path
path:
  pretrain_network_g: models/net_g_s1.pth
  pretrain_network_S1: models/net_g_s2.pth
  param_key_g: params_ema
  strict_load_g: False
  resume_state: ~ 
  ignore_resume_networks: network_S1

# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [500000,700000]
    gamma: 0.5 

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  encoder_iter: 0
  lr_encoder: !!float 2e-4
  lr_sr: !!float 2e-4
  gamma_encoder: 0.1
  gamma_sr: 0.5
  lr_decay_encoder: 60000
  lr_decay_sr: 600000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  kd_opt:
    type: KDLoss
    loss_weight: 1
    temperature: 0.15

# Uncomment these for validation
# validation settings
val:
  window_size: 8
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
